# Item data for Salt and Sanctuary APWorld
from BaseClasses import Item, ItemClassification
from typing import NamedTuple, Dict

BASE_ID = 283640000


class SaltSanctuaryItem(Item):
    game = "Salt and Sanctuary"


class SaltSanctuaryItemData(NamedTuple):
    code: int
    classification: ItemClassification
    game_name: str

item_table: Dict[str, SaltSanctuaryItemData] = {
    "Hardlight Brand": SaltSanctuaryItemData(code=BASE_ID + 0, classification=ItemClassification.progression, game_name="rune_blue_ether"),
    "Dart Brand": SaltSanctuaryItemData(code=BASE_ID + 1, classification=ItemClassification.progression, game_name="rune_dash"),
    "Lift Rune": SaltSanctuaryItemData(code=BASE_ID + 2, classification=ItemClassification.progression, game_name="rune_double_jump"),
    "Redshift Brand": SaltSanctuaryItemData(code=BASE_ID + 3, classification=ItemClassification.progression, game_name="rune_red_block"),
    "Vertigo Brand": SaltSanctuaryItemData(code=BASE_ID + 4, classification=ItemClassification.progression, game_name="rune_upside_down"),
    "Shadowflip Brand": SaltSanctuaryItemData(code=BASE_ID + 5, classification=ItemClassification.progression, game_name="rune_wall_jump"),
    "Bone Key": SaltSanctuaryItemData(code=BASE_ID + 6, classification=ItemClassification.progression, game_name="key_bones"),
    "Bronze Key": SaltSanctuaryItemData(code=BASE_ID + 7, classification=ItemClassification.progression, game_name="key_bronze"),
    "Cellar Key": SaltSanctuaryItemData(code=BASE_ID + 8, classification=ItemClassification.progression, game_name="key_cave"),
    "Jagged Key": SaltSanctuaryItemData(code=BASE_ID + 9, classification=ItemClassification.progression, game_name="key_dungeon"),
    "Mossy Key": SaltSanctuaryItemData(code=BASE_ID + 10, classification=ItemClassification.progression, game_name="key_forest"),
    "Fortress Key": SaltSanctuaryItemData(code=BASE_ID + 11, classification=ItemClassification.progression, game_name="key_fortress"),
    "Green Key": SaltSanctuaryItemData(code=BASE_ID + 12, classification=ItemClassification.progression, game_name="key_green"),
    "Sanctuary Key": SaltSanctuaryItemData(code=BASE_ID + 13, classification=ItemClassification.progression, game_name="key_sanc"),
    "Spiked Key": SaltSanctuaryItemData(code=BASE_ID + 14, classification=ItemClassification.progression, game_name="key_ship"),
    "Bullwhip": SaltSanctuaryItemData(code=BASE_ID + 15, classification=ItemClassification.useful, game_name="whip"),
    "Sacrificial Garrote": SaltSanctuaryItemData(code=BASE_ID + 16, classification=ItemClassification.useful, game_name="whip_bones"),
    "Martial Flail": SaltSanctuaryItemData(code=BASE_ID + 17, classification=ItemClassification.useful, game_name="whip_chain"),
    "Searing Manacle": SaltSanctuaryItemData(code=BASE_ID + 18, classification=ItemClassification.useful, game_name="whip_flame"),
    "Construct Coil": SaltSanctuaryItemData(code=BASE_ID + 19, classification=ItemClassification.useful, game_name="whip_monster"),
    "Scorpion Tail": SaltSanctuaryItemData(code=BASE_ID + 20, classification=ItemClassification.useful, game_name="whip_poison"),
    "Wraithclaw": SaltSanctuaryItemData(code=BASE_ID + 21, classification=ItemClassification.useful, game_name="whip_wraith"),
    "Varangian Spatha": SaltSanctuaryItemData(code=BASE_ID + 22, classification=ItemClassification.useful, game_name="sword"),
    "Kraekan Longsword": SaltSanctuaryItemData(code=BASE_ID + 23, classification=ItemClassification.useful, game_name="sword_bronze"),
    "Red Guillotine": SaltSanctuaryItemData(code=BASE_ID + 24, classification=ItemClassification.useful, game_name="sword_cleaver"),
    "Scharfrichter": SaltSanctuaryItemData(code=BASE_ID + 25, classification=ItemClassification.useful, game_name="sword_cloak"),
    "Chitin Obelisk": SaltSanctuaryItemData(code=BASE_ID + 26, classification=ItemClassification.useful, game_name="sword_crab"),
    "Corsair's Backsword": SaltSanctuaryItemData(code=BASE_ID + 27, classification=ItemClassification.useful, game_name="sword_cutlass"),
    "Trinity Greatsword": SaltSanctuaryItemData(code=BASE_ID + 28, classification=ItemClassification.useful, game_name="sword_deadking"),
    "Shrouded Bulwark": SaltSanctuaryItemData(code=BASE_ID + 29, classification=ItemClassification.useful, game_name="sword_dread"),
    "Branding Iron": SaltSanctuaryItemData(code=BASE_ID + 30, classification=ItemClassification.useful, game_name="sword_flame"),
    "Phoenix Tail": SaltSanctuaryItemData(code=BASE_ID + 31, classification=ItemClassification.useful, game_name="sword_flamewhip"),
    "Flint & Steel": SaltSanctuaryItemData(code=BASE_ID + 32, classification=ItemClassification.useful, game_name="sword_gun"),
    "Tachi": SaltSanctuaryItemData(code=BASE_ID + 33, classification=ItemClassification.useful, game_name="sword_katana"),
    "Lowlander's Greatknife": SaltSanctuaryItemData(code=BASE_ID + 34, classification=ItemClassification.useful, game_name="sword_messer"),
    "Blade of Envy": SaltSanctuaryItemData(code=BASE_ID + 35, classification=ItemClassification.useful, game_name="sword_nameless"),
    "Shikeimaru": SaltSanctuaryItemData(code=BASE_ID + 36, classification=ItemClassification.useful, game_name="sword_onikatana"),
    "Seawolf Cutlass": SaltSanctuaryItemData(code=BASE_ID + 37, classification=ItemClassification.useful, game_name="sword_pirate"),
    "Leviathan": SaltSanctuaryItemData(code=BASE_ID + 38, classification=ItemClassification.useful, game_name="sword_runes"),
    "Virulent Scimitar": SaltSanctuaryItemData(code=BASE_ID + 39, classification=ItemClassification.useful, game_name="sword_rust"),
    "Jaws of Death": SaltSanctuaryItemData(code=BASE_ID + 40, classification=ItemClassification.useful, game_name="sword_scissor"),
    "Northern Cross": SaltSanctuaryItemData(code=BASE_ID + 41, classification=ItemClassification.useful, game_name="sword_sparksor"),
    "Steel Centipede": SaltSanctuaryItemData(code=BASE_ID + 42, classification=ItemClassification.useful, game_name="sword_whip"),
    "Woodsman's Axe": SaltSanctuaryItemData(code=BASE_ID + 43, classification=ItemClassification.useful, game_name="axe"),
    "Castaway's Greatadze": SaltSanctuaryItemData(code=BASE_ID + 44, classification=ItemClassification.useful, game_name="axe_anchor"),
    "Aster Monolith": SaltSanctuaryItemData(code=BASE_ID + 45, classification=ItemClassification.useful, game_name="axe_blue"),
    "Batsuichi Tsuka": SaltSanctuaryItemData(code=BASE_ID + 46, classification=ItemClassification.useful, game_name="axe_broken"),
    "Kraekan Axe": SaltSanctuaryItemData(code=BASE_ID + 47, classification=ItemClassification.useful, game_name="axe_bronze"),
    "Headtaker": SaltSanctuaryItemData(code=BASE_ID + 48, classification=ItemClassification.useful, game_name="axe_bull"),
    "Stone Cleaver": SaltSanctuaryItemData(code=BASE_ID + 49, classification=ItemClassification.useful, game_name="axe_cleaver"),
    "Battle Axe": SaltSanctuaryItemData(code=BASE_ID + 50, classification=ItemClassification.useful, game_name="axe_crescent"),
    "Earthsplitter": SaltSanctuaryItemData(code=BASE_ID + 51, classification=ItemClassification.useful, game_name="axe_crypt"),
    "Raider Axe": SaltSanctuaryItemData(code=BASE_ID + 52, classification=ItemClassification.useful, game_name="axe_double"),
    "Iron Butterfly": SaltSanctuaryItemData(code=BASE_ID + 53, classification=ItemClassification.useful, game_name="axe_giant"),
    "Axe of Splendor": SaltSanctuaryItemData(code=BASE_ID + 54, classification=ItemClassification.useful, game_name="axe_gold"),
    "Outlaw Greataxe": SaltSanctuaryItemData(code=BASE_ID + 55, classification=ItemClassification.useful, game_name="axe_great"),
    "The Coveted": SaltSanctuaryItemData(code=BASE_ID + 56, classification=ItemClassification.useful, game_name="axe_ruins"),
    "Venom Arbelos": SaltSanctuaryItemData(code=BASE_ID + 57, classification=ItemClassification.useful, game_name="axe_tribe"),
    "Morning Star": SaltSanctuaryItemData(code=BASE_ID + 58, classification=ItemClassification.useful, game_name="mace"),
    "Lump Hammer": SaltSanctuaryItemData(code=BASE_ID + 59, classification=ItemClassification.useful, game_name="mace_blacksmith"),
    "Harmen Mace": SaltSanctuaryItemData(code=BASE_ID + 60, classification=ItemClassification.useful, game_name="mace_cruel"),
    "Flanged Mace": SaltSanctuaryItemData(code=BASE_ID + 61, classification=ItemClassification.useful, game_name="mace_flanged"),
    "Mountain Breaker": SaltSanctuaryItemData(code=BASE_ID + 62, classification=ItemClassification.useful, game_name="mace_hammer"),
    "Iron Pot": SaltSanctuaryItemData(code=BASE_ID + 63, classification=ItemClassification.useful, game_name="mace_pot"),
    "Tetruncheon": SaltSanctuaryItemData(code=BASE_ID + 64, classification=ItemClassification.useful, game_name="mace_puffer"),
    "Cephalopounder": SaltSanctuaryItemData(code=BASE_ID + 65, classification=ItemClassification.useful, game_name="mace_squid"),
    "Barbarian's Cudgel": SaltSanctuaryItemData(code=BASE_ID + 66, classification=ItemClassification.useful, game_name="mace_tribe"),
    "Warhammer": SaltSanctuaryItemData(code=BASE_ID + 67, classification=ItemClassification.useful, game_name="hammer_great"),
    "Bonecrusher": SaltSanctuaryItemData(code=BASE_ID + 68, classification=ItemClassification.useful, game_name="hammer_crypt"),
    "Obsidian Pillar": SaltSanctuaryItemData(code=BASE_ID + 69, classification=ItemClassification.useful, game_name="hammer_golem"),
    "Monstrous Mace": SaltSanctuaryItemData(code=BASE_ID + 70, classification=ItemClassification.useful, game_name="hammer_ogre"),
    "Trinity Scepter": SaltSanctuaryItemData(code=BASE_ID + 71, classification=ItemClassification.useful, game_name="hammer_scepter"),
    "Tainted Smithset": SaltSanctuaryItemData(code=BASE_ID + 72, classification=ItemClassification.useful, game_name="bhammer_dark"),
    "Molten Smithset": SaltSanctuaryItemData(code=BASE_ID + 73, classification=ItemClassification.useful, game_name="bhammer_fire"),
    "Frozen Smithset": SaltSanctuaryItemData(code=BASE_ID + 74, classification=ItemClassification.useful, game_name="bhammer_frost"),
    "Divine Smithset": SaltSanctuaryItemData(code=BASE_ID + 75, classification=ItemClassification.useful, game_name="bhammer_holy"),
    "Thunder Smithset": SaltSanctuaryItemData(code=BASE_ID + 76, classification=ItemClassification.useful, game_name="bhammer_lit"),
    "Vile Smithset": SaltSanctuaryItemData(code=BASE_ID + 77, classification=ItemClassification.useful, game_name="bhammer_poison"),
    "Midshipman's Dirk": SaltSanctuaryItemData(code=BASE_ID + 78, classification=ItemClassification.useful, game_name="dagger"),
    "Cutpurse Shiv": SaltSanctuaryItemData(code=BASE_ID + 79, classification=ItemClassification.useful, game_name="dagger_curved"),
    "Eviscerator": SaltSanctuaryItemData(code=BASE_ID + 80, classification=ItemClassification.useful, game_name="dagger_jagged"),
    "Pessklaw": SaltSanctuaryItemData(code=BASE_ID + 81, classification=ItemClassification.useful, game_name="dagger_poison"),
    "Kaltic Razor": SaltSanctuaryItemData(code=BASE_ID + 82, classification=ItemClassification.useful, game_name="dagger_shiv"),
    "Opal Tusk": SaltSanctuaryItemData(code=BASE_ID + 83, classification=ItemClassification.useful, game_name="dagger_white"),
    "Self Bow": SaltSanctuaryItemData(code=BASE_ID + 84, classification=ItemClassification.useful, game_name="bow"),
    "Aegis Greatbow": SaltSanctuaryItemData(code=BASE_ID + 85, classification=ItemClassification.useful, game_name="bow_gold"),
    "Vilehawk Bow": SaltSanctuaryItemData(code=BASE_ID + 86, classification=ItemClassification.useful, game_name="bow_hawk"),
    "Recurve Bow": SaltSanctuaryItemData(code=BASE_ID + 87, classification=ItemClassification.useful, game_name="bow_long"),
    "Bloodwood Bow": SaltSanctuaryItemData(code=BASE_ID + 88, classification=ItemClassification.useful, game_name="bow_red"),
    "Gravewalker Greatbow": SaltSanctuaryItemData(code=BASE_ID + 89, classification=ItemClassification.useful, game_name="bow_stonesoul"),
    "Platoon Crossbow": SaltSanctuaryItemData(code=BASE_ID + 90, classification=ItemClassification.useful, game_name="crossbow"),
    "Predator Lockbow": SaltSanctuaryItemData(code=BASE_ID + 91, classification=ItemClassification.useful, game_name="crossbow_blades"),
    "Hellfire Arbalest": SaltSanctuaryItemData(code=BASE_ID + 92, classification=ItemClassification.useful, game_name="crossbow_dragon"),
    "Adrasteia": SaltSanctuaryItemData(code=BASE_ID + 93, classification=ItemClassification.useful, game_name="crossbow_mummy"),
    "Bloodwood Crossbow": SaltSanctuaryItemData(code=BASE_ID + 94, classification=ItemClassification.useful, game_name="crossbow_red"),
    "Flintlock Pistol": SaltSanctuaryItemData(code=BASE_ID + 95, classification=ItemClassification.useful, game_name="gun_flintlock"),
    "Dragoon Espingole": SaltSanctuaryItemData(code=BASE_ID + 96, classification=ItemClassification.useful, game_name="gun_heavy"),
    "Mosaic Culverin": SaltSanctuaryItemData(code=BASE_ID + 97, classification=ItemClassification.useful, game_name="gun_ruins"),
    "Mephitic Arquebus": SaltSanctuaryItemData(code=BASE_ID + 98, classification=ItemClassification.useful, game_name="gun_teeth"),
    "Lucent Musketoon": SaltSanctuaryItemData(code=BASE_ID + 99, classification=ItemClassification.useful, game_name="gun_white"),
    "Soldier's Spear": SaltSanctuaryItemData(code=BASE_ID + 100, classification=ItemClassification.useful, game_name="spear"),
    "Kumo Sasumata": SaltSanctuaryItemData(code=BASE_ID + 101, classification=ItemClassification.useful, game_name="spear_circle"),
    "Umbral Partisan": SaltSanctuaryItemData(code=BASE_ID + 102, classification=ItemClassification.useful, game_name="spear_cloak"),
    "Razorback": SaltSanctuaryItemData(code=BASE_ID + 103, classification=ItemClassification.useful, game_name="spear_imp"),
    "Oar": SaltSanctuaryItemData(code=BASE_ID + 104, classification=ItemClassification.useful, game_name="spear_oar"),
    "Breach Pike": SaltSanctuaryItemData(code=BASE_ID + 105, classification=ItemClassification.useful, game_name="spear_pilum"),
    "Pitchfork": SaltSanctuaryItemData(code=BASE_ID + 106, classification=ItemClassification.useful, game_name="spear_pitchfork"),
    "Adder Fang": SaltSanctuaryItemData(code=BASE_ID + 107, classification=ItemClassification.useful, game_name="spear_vines"),
    "Overlord's Bident": SaltSanctuaryItemData(code=BASE_ID + 108, classification=ItemClassification.useful, game_name="spear_wicked"),
    "Haymaker": SaltSanctuaryItemData(code=BASE_ID + 109, classification=ItemClassification.useful, game_name="scythe"),
    "Gravedigger": SaltSanctuaryItemData(code=BASE_ID + 110, classification=ItemClassification.useful, game_name="scythe_bones"),
    "Red Eclipse": SaltSanctuaryItemData(code=BASE_ID + 111, classification=ItemClassification.useful, game_name="scythe_moon"),
    "Purifier": SaltSanctuaryItemData(code=BASE_ID + 112, classification=ItemClassification.useful, game_name="scythe_pendulum"),
    "Rusted Greatladle": SaltSanctuaryItemData(code=BASE_ID + 113, classification=ItemClassification.useful, game_name="scythe_spoon"),
    "Saltreaver": SaltSanctuaryItemData(code=BASE_ID + 114, classification=ItemClassification.useful, game_name="scythe_wicked"),
    "Trinity Bardiche": SaltSanctuaryItemData(code=BASE_ID + 115, classification=ItemClassification.useful, game_name="pole_judge"),
    "Headsman's Voulge": SaltSanctuaryItemData(code=BASE_ID + 116, classification=ItemClassification.useful, game_name="pole_pendulum"),
    "Tainted Ranseur": SaltSanctuaryItemData(code=BASE_ID + 117, classification=ItemClassification.useful, game_name="pole_ranseur"),
    "Purgatory Scepter": SaltSanctuaryItemData(code=BASE_ID + 118, classification=ItemClassification.useful, game_name="staff_bones"),
    "Channeler's Rod": SaltSanctuaryItemData(code=BASE_ID + 119, classification=ItemClassification.useful, game_name="staff_conduit"),
    "Scrimshaw Cane": SaltSanctuaryItemData(code=BASE_ID + 120, classification=ItemClassification.useful, game_name="staff_ivory"),
    "Saira's Staff": SaltSanctuaryItemData(code=BASE_ID + 121, classification=ItemClassification.useful, game_name="staff_lakewitch"),
    "Rowan Crosier": SaltSanctuaryItemData(code=BASE_ID + 122, classification=ItemClassification.useful, game_name="staff_wood"),
    "Rostrum Scepter": SaltSanctuaryItemData(code=BASE_ID + 123, classification=ItemClassification.useful, game_name="wand_beak"),
    "Necromancer's Virge": SaltSanctuaryItemData(code=BASE_ID + 124, classification=ItemClassification.useful, game_name="wand_bones"),
    "Cocoon Battledore": SaltSanctuaryItemData(code=BASE_ID + 125, classification=ItemClassification.useful, game_name="wand_butterfly"),
    "Antler Baton": SaltSanctuaryItemData(code=BASE_ID + 126, classification=ItemClassification.useful, game_name="wand_stag"),
    "Saltwood Branch": SaltSanctuaryItemData(code=BASE_ID + 127, classification=ItemClassification.useful, game_name="wand_wood"),
    "Arming Sword": SaltSanctuaryItemData(code=BASE_ID + 128, classification=ItemClassification.useful, game_name="shortsword"),
    "Kureimoa": SaltSanctuaryItemData(code=BASE_ID + 129, classification=ItemClassification.useful, game_name="claymore"),
    "Black Widow": SaltSanctuaryItemData(code=BASE_ID + 130, classification=ItemClassification.useful, game_name="dark_claymore"),
    "Naginata": SaltSanctuaryItemData(code=BASE_ID + 131, classification=ItemClassification.useful, game_name="naginata"),
    "Infantry Pollaxe": SaltSanctuaryItemData(code=BASE_ID + 132, classification=ItemClassification.useful, game_name="halberd"),
    "Guardsman's Halberd": SaltSanctuaryItemData(code=BASE_ID + 133, classification=ItemClassification.useful, game_name="poleaxe"),
    "War Scythe": SaltSanctuaryItemData(code=BASE_ID + 134, classification=ItemClassification.useful, game_name="war_scythe"),
    "Trident": SaltSanctuaryItemData(code=BASE_ID + 135, classification=ItemClassification.useful, game_name="trident"),
    "Stardust Spire": SaltSanctuaryItemData(code=BASE_ID + 136, classification=ItemClassification.useful, game_name="trident_blue"),
    "Rock Shield": SaltSanctuaryItemData(code=BASE_ID + 137, classification=ItemClassification.useful, game_name="rock_shield"),
    "Boeotian Greatshield": SaltSanctuaryItemData(code=BASE_ID + 138, classification=ItemClassification.useful, game_name="shield_antler"),
    "Escutcheon": SaltSanctuaryItemData(code=BASE_ID + 139, classification=ItemClassification.useful, game_name="shield_banner"),
    "Umbral Aegis": SaltSanctuaryItemData(code=BASE_ID + 140, classification=ItemClassification.useful, game_name="shield_black"),
    "Pruina Scutum": SaltSanctuaryItemData(code=BASE_ID + 141, classification=ItemClassification.useful, game_name="shield_blue"),
    "Vinemesh Peltarion": SaltSanctuaryItemData(code=BASE_ID + 142, classification=ItemClassification.useful, game_name="shield_branches"),
    "Kraekan Greatshield": SaltSanctuaryItemData(code=BASE_ID + 143, classification=ItemClassification.useful, game_name="shield_bronze"),
    "Buckler": SaltSanctuaryItemData(code=BASE_ID + 144, classification=ItemClassification.useful, game_name="shield_buckler"),
    "Carapace Pavise": SaltSanctuaryItemData(code=BASE_ID + 145, classification=ItemClassification.useful, game_name="shield_bug"),
    "Cleric's Kite Shield": SaltSanctuaryItemData(code=BASE_ID + 146, classification=ItemClassification.useful, game_name="shield_cleric"),
    "Oppressor's Greatshield": SaltSanctuaryItemData(code=BASE_ID + 147, classification=ItemClassification.useful, game_name="shield_dread"),
    "Iron Rampart": SaltSanctuaryItemData(code=BASE_ID + 148, classification=ItemClassification.useful, game_name="shield_golem"),
    "Heater Shield": SaltSanctuaryItemData(code=BASE_ID + 149, classification=ItemClassification.useful, game_name="shield_heater"),
    "Teuthis Shield": SaltSanctuaryItemData(code=BASE_ID + 150, classification=ItemClassification.useful, game_name="shield_iron"),
    "Mirror Shield": SaltSanctuaryItemData(code=BASE_ID + 151, classification=ItemClassification.useful, game_name="shield_ornate"),
    "Askarian Scutum": SaltSanctuaryItemData(code=BASE_ID + 152, classification=ItemClassification.useful, game_name="shield_oval"),
    "Palatine Kite Shield": SaltSanctuaryItemData(code=BASE_ID + 153, classification=ItemClassification.useful, game_name="shield_paladin"),
    "Flayer's Rack": SaltSanctuaryItemData(code=BASE_ID + 154, classification=ItemClassification.useful, game_name="shield_rotten"),
    "Phoenix Rondache": SaltSanctuaryItemData(code=BASE_ID + 155, classification=ItemClassification.useful, game_name="shield_round"),
    "Tainted Greatshield": SaltSanctuaryItemData(code=BASE_ID + 156, classification=ItemClassification.useful, game_name="shield_saltknight"),
    "Silver Shield": SaltSanctuaryItemData(code=BASE_ID + 157, classification=ItemClassification.useful, game_name="shield_silver"),
    "Ashen Effigy": SaltSanctuaryItemData(code=BASE_ID + 158, classification=ItemClassification.useful, game_name="shield_skulls"),
    "Pendragon Targe": SaltSanctuaryItemData(code=BASE_ID + 159, classification=ItemClassification.useful, game_name="shield_snakes"),
    "Type 46 Tower Shield": SaltSanctuaryItemData(code=BASE_ID + 160, classification=ItemClassification.useful, game_name="shield_tower"),
    "Sunset Kite Shield": SaltSanctuaryItemData(code=BASE_ID + 161, classification=ItemClassification.useful, game_name="shield_tree"),
    "Raider's Targe": SaltSanctuaryItemData(code=BASE_ID + 162, classification=ItemClassification.useful, game_name="shield_viking"),
    "Bloodbrow Scutum": SaltSanctuaryItemData(code=BASE_ID + 163, classification=ItemClassification.useful, game_name="shield_whispers"),
    "Wooden Targe": SaltSanctuaryItemData(code=BASE_ID + 164, classification=ItemClassification.useful, game_name="shield_wood"),
    "Gangplank Mantlet": SaltSanctuaryItemData(code=BASE_ID + 165, classification=ItemClassification.useful, game_name="shield_wood_tower"),
    "Bloodflower Charm": SaltSanctuaryItemData(code=BASE_ID + 166, classification=ItemClassification.useful, game_name="charm_atk"),
    "Black Charm": SaltSanctuaryItemData(code=BASE_ID + 167, classification=ItemClassification.useful, game_name="charm_cursed"),
    "Shroud Charm": SaltSanctuaryItemData(code=BASE_ID + 168, classification=ItemClassification.useful, game_name="charm_dark"),
    "Redhair Charm": SaltSanctuaryItemData(code=BASE_ID + 169, classification=ItemClassification.useful, game_name="charm_dying_overkill"),
    "Whistlebone Charm": SaltSanctuaryItemData(code=BASE_ID + 170, classification=ItemClassification.useful, game_name="charm_ease"),
    "Impen's Charm": SaltSanctuaryItemData(code=BASE_ID + 171, classification=ItemClassification.useful, game_name="charm_fire"),
    "Frozen Charm": SaltSanctuaryItemData(code=BASE_ID + 172, classification=ItemClassification.useful, game_name="charm_frost"),
    "Mireheart Charm": SaltSanctuaryItemData(code=BASE_ID + 173, classification=ItemClassification.useful, game_name="charm_heavy_poison"),
    "Templar's Charm": SaltSanctuaryItemData(code=BASE_ID + 174, classification=ItemClassification.useful, game_name="charm_holy"),
    "Voracious Charm": SaltSanctuaryItemData(code=BASE_ID + 175, classification=ItemClassification.useful, game_name="charm_hp_leech"),
    "Lantern Charm": SaltSanctuaryItemData(code=BASE_ID + 176, classification=ItemClassification.useful, game_name="charm_lantern"),
    "Goldenstone Charm": SaltSanctuaryItemData(code=BASE_ID + 177, classification=ItemClassification.useful, game_name="charm_lit"),
    "Saper Charm": SaltSanctuaryItemData(code=BASE_ID + 178, classification=ItemClassification.useful, game_name="charm_mp_leech"),
    "Stone Charm": SaltSanctuaryItemData(code=BASE_ID + 179, classification=ItemClassification.useful, game_name="charm_poise"),
    "Vile Charm": SaltSanctuaryItemData(code=BASE_ID + 180, classification=ItemClassification.useful, game_name="charm_poison"),
    "Pale Charm": SaltSanctuaryItemData(code=BASE_ID + 181, classification=ItemClassification.useful, game_name="charm_reach"),
    "Silversalt Charm": SaltSanctuaryItemData(code=BASE_ID + 182, classification=ItemClassification.useful, game_name="charm_salt_overload"),
    "Mossy Charm": SaltSanctuaryItemData(code=BASE_ID + 183, classification=ItemClassification.useful, game_name="charm_speed"),
    "Bloodluster's Ring": SaltSanctuaryItemData(code=BASE_ID + 184, classification=ItemClassification.useful, game_name="ring_bloody"),
    "Burning Sky Ring": SaltSanctuaryItemData(code=BASE_ID + 185, classification=ItemClassification.useful, game_name="ring_cheap_mag"),
    "Ring of Meditation": SaltSanctuaryItemData(code=BASE_ID + 186, classification=ItemClassification.useful, game_name="ring_cheap_wis"),
    "Bloodflower Ring": SaltSanctuaryItemData(code=BASE_ID + 187, classification=ItemClassification.useful, game_name="ring_damage"),
    "Defender's Ring": SaltSanctuaryItemData(code=BASE_ID + 188, classification=ItemClassification.useful, game_name="ring_def"),
    "Trickster's Band": SaltSanctuaryItemData(code=BASE_ID + 189, classification=ItemClassification.useful, game_name="ring_dex"),
    "Corroded Ring": SaltSanctuaryItemData(code=BASE_ID + 190, classification=ItemClassification.useful, game_name="ring_fire_dmg"),
    "Fused Metal Ring": SaltSanctuaryItemData(code=BASE_ID + 191, classification=ItemClassification.useful, game_name="ring_fort"),
    "Symbol of Affluence": SaltSanctuaryItemData(code=BASE_ID + 192, classification=ItemClassification.useful, game_name="ring_gold"),
    "Sparkling Ring": SaltSanctuaryItemData(code=BASE_ID + 193, classification=ItemClassification.useful, game_name="ring_heal"),
    "Mending Band": SaltSanctuaryItemData(code=BASE_ID + 194, classification=ItemClassification.useful, game_name="ring_hp"),
    "Heartspent Ring": SaltSanctuaryItemData(code=BASE_ID + 195, classification=ItemClassification.useful, game_name="ring_hp_mp"),
    "Kismet Stone": SaltSanctuaryItemData(code=BASE_ID + 196, classification=ItemClassification.useful, game_name="ring_itemfind"),
    "Ring of Brilliance": SaltSanctuaryItemData(code=BASE_ID + 197, classification=ItemClassification.useful, game_name="ring_light"),
    "Hurrrrd Ring": SaltSanctuaryItemData(code=BASE_ID + 198, classification=ItemClassification.useful, game_name="ring_luck"),
    "Link of Fire and Sky": SaltSanctuaryItemData(code=BASE_ID + 199, classification=ItemClassification.useful, game_name="ring_mag_balance"),
    "Storm Ring": SaltSanctuaryItemData(code=BASE_ID + 200, classification=ItemClassification.useful, game_name="ring_mag_boost"),
    "Charged Ring": SaltSanctuaryItemData(code=BASE_ID + 201, classification=ItemClassification.useful, game_name="ring_magic"),
    "Twinmetal Ring": SaltSanctuaryItemData(code=BASE_ID + 202, classification=ItemClassification.useful, game_name="ring_melee"),
    "Conduit of Mind": SaltSanctuaryItemData(code=BASE_ID + 203, classification=ItemClassification.useful, game_name="ring_mp"),
    "Crystalmoat Ring": SaltSanctuaryItemData(code=BASE_ID + 204, classification=ItemClassification.useful, game_name="ring_mp_moat"),
    "Stone Ring": SaltSanctuaryItemData(code=BASE_ID + 205, classification=ItemClassification.useful, game_name="ring_poise"),
    "Wrapped Link": SaltSanctuaryItemData(code=BASE_ID + 206, classification=ItemClassification.useful, game_name="ring_roll"),
    "Grasping Ring": SaltSanctuaryItemData(code=BASE_ID + 207, classification=ItemClassification.useful, game_name="ring_salt"),
    "Salt Seeker's Ring": SaltSanctuaryItemData(code=BASE_ID + 208, classification=ItemClassification.useful, game_name="ring_saltseek"),
    "Dancing Ring": SaltSanctuaryItemData(code=BASE_ID + 209, classification=ItemClassification.useful, game_name="ring_slash"),
    "Relentless Ring": SaltSanctuaryItemData(code=BASE_ID + 210, classification=ItemClassification.useful, game_name="ring_spirit"),
    "Brightcoral Ring": SaltSanctuaryItemData(code=BASE_ID + 211, classification=ItemClassification.useful, game_name="ring_stam"),
    "Mossy Ring": SaltSanctuaryItemData(code=BASE_ID + 212, classification=ItemClassification.useful, game_name="ring_stamina"),
    "Plated Band": SaltSanctuaryItemData(code=BASE_ID + 213, classification=ItemClassification.useful, game_name="ring_str"),
    "Bandaged Ring": SaltSanctuaryItemData(code=BASE_ID + 214, classification=ItemClassification.useful, game_name="ring_vit"),
    "Band of the Humble": SaltSanctuaryItemData(code=BASE_ID + 215, classification=ItemClassification.useful, game_name="ring_wisdom"),
    "Impen Crest Ring": SaltSanctuaryItemData(code=BASE_ID + 216, classification=ItemClassification.useful, game_name="fire_def"),
    "Gurrrrrd Ring": SaltSanctuaryItemData(code=BASE_ID + 217, classification=ItemClassification.useful, game_name="frost_def"),
    "Shroud Ring": SaltSanctuaryItemData(code=BASE_ID + 218, classification=ItemClassification.useful, game_name="holy_def"),
    "Goldenstone Ring": SaltSanctuaryItemData(code=BASE_ID + 219, classification=ItemClassification.useful, game_name="lit_def"),
    "Vile Vines Ring": SaltSanctuaryItemData(code=BASE_ID + 220, classification=ItemClassification.useful, game_name="poison_def"),
    "Faithful Ring": SaltSanctuaryItemData(code=BASE_ID + 221, classification=ItemClassification.useful, game_name="dark_def"),
    "Mend": SaltSanctuaryItemData(code=BASE_ID + 222, classification=ItemClassification.useful, game_name="heal"),
    "Spirited Mend": SaltSanctuaryItemData(code=BASE_ID + 223, classification=ItemClassification.useful, game_name="heal2"),
    "Rejuvenate": SaltSanctuaryItemData(code=BASE_ID + 224, classification=ItemClassification.useful, game_name="heal3"),
    "Fireball": SaltSanctuaryItemData(code=BASE_ID + 225, classification=ItemClassification.useful, game_name="fire2"),
    "Wildfire": SaltSanctuaryItemData(code=BASE_ID + 226, classification=ItemClassification.useful, game_name="flame_storm"),
    "Flame Barrage": SaltSanctuaryItemData(code=BASE_ID + 227, classification=ItemClassification.useful, game_name="rapid_fire"),
    "Lightning Ball": SaltSanctuaryItemData(code=BASE_ID + 228, classification=ItemClassification.useful, game_name="lit_ball"),
    "Lightning Bolt": SaltSanctuaryItemData(code=BASE_ID + 229, classification=ItemClassification.useful, game_name="lit_bolt"),
    "Lightning Arc": SaltSanctuaryItemData(code=BASE_ID + 230, classification=ItemClassification.useful, game_name="lit_bolt2"),
    "Static Geist": SaltSanctuaryItemData(code=BASE_ID + 231, classification=ItemClassification.useful, game_name="lit_ghost"),
    "Lightning Pod": SaltSanctuaryItemData(code=BASE_ID + 232, classification=ItemClassification.useful, game_name="lit_satellite"),
    "Lightning Storm": SaltSanctuaryItemData(code=BASE_ID + 233, classification=ItemClassification.useful, game_name="lit_storm"),
    "Lightning Barrage": SaltSanctuaryItemData(code=BASE_ID + 234, classification=ItemClassification.useful, game_name="rapid_lit"),
    "Flame Guardian": SaltSanctuaryItemData(code=BASE_ID + 235, classification=ItemClassification.useful, game_name="fire_turret"),
    "Flame Orbiters": SaltSanctuaryItemData(code=BASE_ID + 236, classification=ItemClassification.useful, game_name="fire_oribts"),
    "Guardian Blade": SaltSanctuaryItemData(code=BASE_ID + 237, classification=ItemClassification.useful, game_name="holy_blade"),
    "Blessed Weapon": SaltSanctuaryItemData(code=BASE_ID + 238, classification=ItemClassification.useful, game_name="holy_buff"),
    "Divine Blessed Weapon": SaltSanctuaryItemData(code=BASE_ID + 239, classification=ItemClassification.useful, game_name="holy_buff2"),
    "Cleanse": SaltSanctuaryItemData(code=BASE_ID + 240, classification=ItemClassification.useful, game_name="holy_cleanse"),
    "Ray of Searing": SaltSanctuaryItemData(code=BASE_ID + 241, classification=ItemClassification.useful, game_name="holy_cone"),
    "Light": SaltSanctuaryItemData(code=BASE_ID + 242, classification=ItemClassification.useful, game_name="holy_light"),
    "Ethereal Intervention": SaltSanctuaryItemData(code=BASE_ID + 243, classification=ItemClassification.useful, game_name="holy_mag_def"),
    "Sprites": SaltSanctuaryItemData(code=BASE_ID + 244, classification=ItemClassification.useful, game_name="holy_orbits"),
    "Divine Armor": SaltSanctuaryItemData(code=BASE_ID + 245, classification=ItemClassification.useful, game_name="holy_phys_def"),
    "Revive": SaltSanctuaryItemData(code=BASE_ID + 246, classification=ItemClassification.useful, game_name="holy_revive"),
    "Divine Will": SaltSanctuaryItemData(code=BASE_ID + 247, classification=ItemClassification.useful, game_name="holy_will"),
    "Arcane Weapon": SaltSanctuaryItemData(code=BASE_ID + 248, classification=ItemClassification.useful, game_name="mag_dark_buff"),
    "Dark Swarm": SaltSanctuaryItemData(code=BASE_ID + 249, classification=ItemClassification.useful, game_name="mag_dark_witch"),
    "Dragonfire": SaltSanctuaryItemData(code=BASE_ID + 250, classification=ItemClassification.useful, game_name="mag_dragon_fire"),
    "Flamestar": SaltSanctuaryItemData(code=BASE_ID + 251, classification=ItemClassification.useful, game_name="mag_firestar"),
    "Venomous Blade": SaltSanctuaryItemData(code=BASE_ID + 252, classification=ItemClassification.useful, game_name="mag_poison_buff"),
    "Poison Gas": SaltSanctuaryItemData(code=BASE_ID + 253, classification=ItemClassification.useful, game_name="mag_poison_gas"),
    "Undersight": SaltSanctuaryItemData(code=BASE_ID + 254, classification=ItemClassification.useful, game_name="mag_vision_buff"),
    "Dark Arrows": SaltSanctuaryItemData(code=BASE_ID + 255, classification=ItemClassification.useful, game_name="mag_witch_laser"),
    "Alchemist's Coverall": SaltSanctuaryItemData(code=BASE_ID + 256, classification=ItemClassification.filler, game_name="alchemist_armor"),
    "Alchemist's Apron": SaltSanctuaryItemData(code=BASE_ID + 257, classification=ItemClassification.filler, game_name="alchemist_boots"),
    "Alchemist's Mask": SaltSanctuaryItemData(code=BASE_ID + 258, classification=ItemClassification.filler, game_name="alchemist_helm"),
    "Blacksmith's Apron": SaltSanctuaryItemData(code=BASE_ID + 259, classification=ItemClassification.filler, game_name="blacksmith_armor"),
    "Blacksmith's Boots": SaltSanctuaryItemData(code=BASE_ID + 260, classification=ItemClassification.filler, game_name="blacksmith_boots"),
    "Blacksmith's Gloves": SaltSanctuaryItemData(code=BASE_ID + 261, classification=ItemClassification.filler, game_name="blacksmith_gloves"),
    "Onyx Cuirass": SaltSanctuaryItemData(code=BASE_ID + 262, classification=ItemClassification.filler, game_name="black_armor"),
    "Onyx Sabatons": SaltSanctuaryItemData(code=BASE_ID + 263, classification=ItemClassification.filler, game_name="black_boots"),
    "Onyx Manifers": SaltSanctuaryItemData(code=BASE_ID + 264, classification=ItemClassification.filler, game_name="black_gloves"),
    "Onyx Burgeonet": SaltSanctuaryItemData(code=BASE_ID + 265, classification=ItemClassification.filler, game_name="black_helm"),
    "Lamprey Cuirass": SaltSanctuaryItemData(code=BASE_ID + 266, classification=ItemClassification.filler, game_name="blades_armor"),
    "Lamprey Greaves": SaltSanctuaryItemData(code=BASE_ID + 267, classification=ItemClassification.filler, game_name="blades_boots"),
    "Lamprey Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 268, classification=ItemClassification.filler, game_name="blades_gloves"),
    "Lamprey Barbut": SaltSanctuaryItemData(code=BASE_ID + 269, classification=ItemClassification.filler, game_name="blades_helm"),
    "Stella Soprana": SaltSanctuaryItemData(code=BASE_ID + 270, classification=ItemClassification.filler, game_name="bluering_armor"),
    "Stella Cincture": SaltSanctuaryItemData(code=BASE_ID + 271, classification=ItemClassification.filler, game_name="bluering_boots"),
    "Stella Guanti": SaltSanctuaryItemData(code=BASE_ID + 272, classification=ItemClassification.filler, game_name="bluering_gloves"),
    "Stella Triregno": SaltSanctuaryItemData(code=BASE_ID + 273, classification=ItemClassification.filler, game_name="bluering_helm"),
    "Boatman's Mino": SaltSanctuaryItemData(code=BASE_ID + 274, classification=ItemClassification.filler, game_name="boat_armor"),
    "Boatman's Waraji": SaltSanctuaryItemData(code=BASE_ID + 275, classification=ItemClassification.filler, game_name="boat_boots"),
    "Boatman's Sugegasa": SaltSanctuaryItemData(code=BASE_ID + 276, classification=ItemClassification.filler, game_name="boat_helm"),
    "Kraekan Armor": SaltSanctuaryItemData(code=BASE_ID + 277, classification=ItemClassification.filler, game_name="bronze_armor"),
    "Kraekan Greaves": SaltSanctuaryItemData(code=BASE_ID + 278, classification=ItemClassification.filler, game_name="bronze_boots"),
    "Kraekan Gloves": SaltSanctuaryItemData(code=BASE_ID + 279, classification=ItemClassification.filler, game_name="bronze_gloves"),
    "Kraekan Helm": SaltSanctuaryItemData(code=BASE_ID + 280, classification=ItemClassification.filler, game_name="bronze_helm"),
    "Officer's Frock Coat": SaltSanctuaryItemData(code=BASE_ID + 281, classification=ItemClassification.filler, game_name="captain_armor"),
    "Officer's Jackboots": SaltSanctuaryItemData(code=BASE_ID + 282, classification=ItemClassification.filler, game_name="captain_boots"),
    "Chain Hauberk": SaltSanctuaryItemData(code=BASE_ID + 283, classification=ItemClassification.filler, game_name="chain_armor"),
    "Chain Chausses": SaltSanctuaryItemData(code=BASE_ID + 284, classification=ItemClassification.filler, game_name="chain_boots"),
    "Chain Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 285, classification=ItemClassification.filler, game_name="chain_gloves"),
    "Chain Coif": SaltSanctuaryItemData(code=BASE_ID + 286, classification=ItemClassification.filler, game_name="chain_helm"),
    "Chef's Apron": SaltSanctuaryItemData(code=BASE_ID + 287, classification=ItemClassification.filler, game_name="chef_armor"),
    "Chef's Trousers": SaltSanctuaryItemData(code=BASE_ID + 288, classification=ItemClassification.filler, game_name="chef_boots"),
    "Chef's Toque": SaltSanctuaryItemData(code=BASE_ID + 289, classification=ItemClassification.filler, game_name="chef_helm"),
    "Priest's Dalmatic": SaltSanctuaryItemData(code=BASE_ID + 290, classification=ItemClassification.filler, game_name="cleric_armor"),
    "Priest's Sabots": SaltSanctuaryItemData(code=BASE_ID + 291, classification=ItemClassification.filler, game_name="cleric_boots"),
    "Priest's Zucchetto": SaltSanctuaryItemData(code=BASE_ID + 292, classification=ItemClassification.filler, game_name="cleric_helm"),
    "Umbral Shroud": SaltSanctuaryItemData(code=BASE_ID + 293, classification=ItemClassification.filler, game_name="cloak_armor"),
    "Umbral Rhinegraves": SaltSanctuaryItemData(code=BASE_ID + 294, classification=ItemClassification.filler, game_name="cloak_boots"),
    "Umbral Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 295, classification=ItemClassification.filler, game_name="cloak_gloves"),
    "Umbral Visor": SaltSanctuaryItemData(code=BASE_ID + 296, classification=ItemClassification.filler, game_name="cloak_helm"),
    "Golem's Torso": SaltSanctuaryItemData(code=BASE_ID + 297, classification=ItemClassification.filler, game_name="crypt_armor"),
    "Golem's Legs": SaltSanctuaryItemData(code=BASE_ID + 298, classification=ItemClassification.filler, game_name="crypt_boots"),
    "Golem's Arms": SaltSanctuaryItemData(code=BASE_ID + 299, classification=ItemClassification.filler, game_name="crypt_gloves"),
    "Golem's Head": SaltSanctuaryItemData(code=BASE_ID + 300, classification=ItemClassification.filler, game_name="crypt_helm"),
    "Mildewed Chemise": SaltSanctuaryItemData(code=BASE_ID + 301, classification=ItemClassification.filler, game_name="cutqueen_armor"),
    "Mildewed Polonaise": SaltSanctuaryItemData(code=BASE_ID + 302, classification=ItemClassification.filler, game_name="cutqueen_boots"),
    "Mildewed Caraco": SaltSanctuaryItemData(code=BASE_ID + 303, classification=ItemClassification.filler, game_name="cutqueen_gloves"),
    "Tarnished Coronet": SaltSanctuaryItemData(code=BASE_ID + 304, classification=ItemClassification.filler, game_name="cutqueen_helm"),
    "Black Tailcoat": SaltSanctuaryItemData(code=BASE_ID + 305, classification=ItemClassification.filler, game_name="dapper_armor"),
    "Black Slacks": SaltSanctuaryItemData(code=BASE_ID + 306, classification=ItemClassification.filler, game_name="dapper_boots"),
    "Black Silk Gloves": SaltSanctuaryItemData(code=BASE_ID + 307, classification=ItemClassification.filler, game_name="dapper_gloves"),
    "Top Hat": SaltSanctuaryItemData(code=BASE_ID + 308, classification=ItemClassification.filler, game_name="dapper_helm"),
    "Bloodbrow Cuirass": SaltSanctuaryItemData(code=BASE_ID + 309, classification=ItemClassification.filler, game_name="devil_armor"),
    "Bloodbrow Greaves": SaltSanctuaryItemData(code=BASE_ID + 310, classification=ItemClassification.filler, game_name="devil_boots"),
    "Bloodbrow Barbute": SaltSanctuaryItemData(code=BASE_ID + 311, classification=ItemClassification.filler, game_name="devil_helm"),
    "Ragged Hanten": SaltSanctuaryItemData(code=BASE_ID + 312, classification=ItemClassification.filler, game_name="dish_armor"),
    "Ragged Hakama": SaltSanctuaryItemData(code=BASE_ID + 313, classification=ItemClassification.filler, game_name="dish_boots"),
    "Silver Udewa": SaltSanctuaryItemData(code=BASE_ID + 314, classification=ItemClassification.filler, game_name="dish_gloves"),
    "Frayed Sugegasa": SaltSanctuaryItemData(code=BASE_ID + 315, classification=ItemClassification.filler, game_name="dish_helm"),
    "Cavalier's Cuirass": SaltSanctuaryItemData(code=BASE_ID + 316, classification=ItemClassification.filler, game_name="dread_armor"),
    "Cavalier's Sabatons": SaltSanctuaryItemData(code=BASE_ID + 317, classification=ItemClassification.filler, game_name="dread_boots"),
    "Cavalier's Manifers": SaltSanctuaryItemData(code=BASE_ID + 318, classification=ItemClassification.filler, game_name="dread_gloves"),
    "Cavalier's Armet": SaltSanctuaryItemData(code=BASE_ID + 319, classification=ItemClassification.filler, game_name="dread_helm"),
    "Scorpion Krug": SaltSanctuaryItemData(code=BASE_ID + 320, classification=ItemClassification.filler, game_name="fat_armor"),
    "Scorpion Dizcek": SaltSanctuaryItemData(code=BASE_ID + 321, classification=ItemClassification.filler, game_name="fat_boots"),
    "Scorpion Kolluk": SaltSanctuaryItemData(code=BASE_ID + 322, classification=ItemClassification.filler, game_name="fat_gloves"),
    "Scorpion Migfer": SaltSanctuaryItemData(code=BASE_ID + 323, classification=ItemClassification.filler, game_name="fat_helm"),
    "Titan Cuirass": SaltSanctuaryItemData(code=BASE_ID + 324, classification=ItemClassification.filler, game_name="golem_armor"),
    "Titan Greaves": SaltSanctuaryItemData(code=BASE_ID + 325, classification=ItemClassification.filler, game_name="golem_boots"),
    "Titan Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 326, classification=ItemClassification.filler, game_name="golem_gloves"),
    "Titan Armet": SaltSanctuaryItemData(code=BASE_ID + 327, classification=ItemClassification.filler, game_name="golem_helm"),
    "Guide's Tunic": SaltSanctuaryItemData(code=BASE_ID + 328, classification=ItemClassification.filler, game_name="guide_armor"),
    "Guide's Trousers": SaltSanctuaryItemData(code=BASE_ID + 329, classification=ItemClassification.filler, game_name="guide_boots"),
    "Guide's Gloves": SaltSanctuaryItemData(code=BASE_ID + 330, classification=ItemClassification.filler, game_name="guide_gloves"),
    "Guide's Cap": SaltSanctuaryItemData(code=BASE_ID + 331, classification=ItemClassification.filler, game_name="guide_helm"),
    "Raptor Brigandine": SaltSanctuaryItemData(code=BASE_ID + 332, classification=ItemClassification.filler, game_name="hawk_armor"),
    "Raptor Sabatons": SaltSanctuaryItemData(code=BASE_ID + 333, classification=ItemClassification.filler, game_name="hawk_boots"),
    "Raptor Visor": SaltSanctuaryItemData(code=BASE_ID + 334, classification=ItemClassification.filler, game_name="hawk_helm"),
    "Resplendent Cuirass": SaltSanctuaryItemData(code=BASE_ID + 335, classification=ItemClassification.filler, game_name="heavygold_armor"),
    "Resplendent Cuisses": SaltSanctuaryItemData(code=BASE_ID + 336, classification=ItemClassification.filler, game_name="heavygold_boots"),
    "Resplendent Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 337, classification=ItemClassification.filler, game_name="heavygold_gloves"),
    "Resplendent Armet": SaltSanctuaryItemData(code=BASE_ID + 338, classification=ItemClassification.filler, game_name="heavygold_helm"),
    "Hunter's Cloak": SaltSanctuaryItemData(code=BASE_ID + 339, classification=ItemClassification.filler, game_name="hunter_armor"),
    "Hunter's Boots": SaltSanctuaryItemData(code=BASE_ID + 340, classification=ItemClassification.filler, game_name="hunter_boots"),
    "Hunter's Gloves": SaltSanctuaryItemData(code=BASE_ID + 341, classification=ItemClassification.filler, game_name="hunter_gloves"),
    "Hunter's Tricorne": SaltSanctuaryItemData(code=BASE_ID + 342, classification=ItemClassification.filler, game_name="hunter_helm"),
    "Jester's Motley": SaltSanctuaryItemData(code=BASE_ID + 343, classification=ItemClassification.filler, game_name="jester_armor"),
    "Jester's Slippers": SaltSanctuaryItemData(code=BASE_ID + 344, classification=ItemClassification.filler, game_name="jester_boots"),
    "Jester's Crown": SaltSanctuaryItemData(code=BASE_ID + 345, classification=ItemClassification.filler, game_name="jester_helm"),
    "Steel Cuirass": SaltSanctuaryItemData(code=BASE_ID + 346, classification=ItemClassification.filler, game_name="knight_armor"),
    "Steel Greaves": SaltSanctuaryItemData(code=BASE_ID + 347, classification=ItemClassification.filler, game_name="knight_boots"),
    "Steel Manifers": SaltSanctuaryItemData(code=BASE_ID + 348, classification=ItemClassification.filler, game_name="knight_gloves"),
    "Steel Armet": SaltSanctuaryItemData(code=BASE_ID + 349, classification=ItemClassification.filler, game_name="knight_helm"),
    "Fleshbound Basque": SaltSanctuaryItemData(code=BASE_ID + 350, classification=ItemClassification.filler, game_name="lakewitch_armor"),
    "Fleshbound Frock": SaltSanctuaryItemData(code=BASE_ID + 351, classification=ItemClassification.filler, game_name="lakewitch_boots"),
    "Steepled Hat": SaltSanctuaryItemData(code=BASE_ID + 352, classification=ItemClassification.filler, game_name="lakewitch_helm"),
    "Leather Cuirass": SaltSanctuaryItemData(code=BASE_ID + 353, classification=ItemClassification.filler, game_name="leather_armor"),
    "Leather Cuisses": SaltSanctuaryItemData(code=BASE_ID + 354, classification=ItemClassification.filler, game_name="leather_boots"),
    "Leather Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 355, classification=ItemClassification.filler, game_name="leather_gloves"),
    "Leather Sallet": SaltSanctuaryItemData(code=BASE_ID + 356, classification=ItemClassification.filler, game_name="leather_helm"),
    "Acolyte's Kontusz": SaltSanctuaryItemData(code=BASE_ID + 357, classification=ItemClassification.filler, game_name="mage_armor"),
    "Acolyte's Boots": SaltSanctuaryItemData(code=BASE_ID + 358, classification=ItemClassification.filler, game_name="mage_boots"),
    "Acolyte's Gloves": SaltSanctuaryItemData(code=BASE_ID + 359, classification=ItemClassification.filler, game_name="mage_gloves"),
    "Merchant's Dolman": SaltSanctuaryItemData(code=BASE_ID + 360, classification=ItemClassification.filler, game_name="merchant_armor"),
    "Merchant's Fistan": SaltSanctuaryItemData(code=BASE_ID + 361, classification=ItemClassification.filler, game_name="merchant_boots"),
    "Merchant's Gloves": SaltSanctuaryItemData(code=BASE_ID + 362, classification=ItemClassification.filler, game_name="merchant_gloves"),
    "Merchant's Fez": SaltSanctuaryItemData(code=BASE_ID + 363, classification=ItemClassification.filler, game_name="merchant_helm"),
    "Sohei Kesa": SaltSanctuaryItemData(code=BASE_ID + 364, classification=ItemClassification.filler, game_name="monk_armor"),
    "Sohei Tabi": SaltSanctuaryItemData(code=BASE_ID + 365, classification=ItemClassification.filler, game_name="monk_boots"),
    "Juzu-udewa": SaltSanctuaryItemData(code=BASE_ID + 366, classification=ItemClassification.filler, game_name="monk_gloves"),
    "Alkymancer's Simar": SaltSanctuaryItemData(code=BASE_ID + 367, classification=ItemClassification.filler, game_name="monsterwitch_armor"),
    "Alkymancer's Gown": SaltSanctuaryItemData(code=BASE_ID + 368, classification=ItemClassification.filler, game_name="monsterwitch_boots"),
    "Alkymancer's Veil": SaltSanctuaryItemData(code=BASE_ID + 369, classification=ItemClassification.filler, game_name="monsterwitch_helm"),
    "Overlord's Candelabra": SaltSanctuaryItemData(code=BASE_ID + 370, classification=ItemClassification.filler, game_name="nameless_armor"),
    "Overlord's Greaves": SaltSanctuaryItemData(code=BASE_ID + 371, classification=ItemClassification.filler, game_name="nameless_boots"),
    "Overlord's Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 372, classification=ItemClassification.filler, game_name="nameless_gloves"),
    "Overlord's Turban": SaltSanctuaryItemData(code=BASE_ID + 373, classification=ItemClassification.filler, game_name="nameless_helm"),
    "Assassin's Tunic": SaltSanctuaryItemData(code=BASE_ID + 374, classification=ItemClassification.filler, game_name="ninja_armor"),
    "Assassin's Leggings": SaltSanctuaryItemData(code=BASE_ID + 375, classification=ItemClassification.filler, game_name="ninja_boots"),
    "Assassin's Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 376, classification=ItemClassification.filler, game_name="ninja_gloves"),
    "Assassin's Cowl": SaltSanctuaryItemData(code=BASE_ID + 377, classification=ItemClassification.filler, game_name="ninja_helm"),
    "Palatine Chainmail": SaltSanctuaryItemData(code=BASE_ID + 378, classification=ItemClassification.filler, game_name="paladin_armor"),
    "Palatine Chausses": SaltSanctuaryItemData(code=BASE_ID + 379, classification=ItemClassification.filler, game_name="paladin_boots"),
    "Palatine Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 380, classification=ItemClassification.filler, game_name="paladin_gloves"),
    "Palatine Coif": SaltSanctuaryItemData(code=BASE_ID + 381, classification=ItemClassification.filler, game_name="paladin_helm"),
    "Patched Rags": SaltSanctuaryItemData(code=BASE_ID + 382, classification=ItemClassification.filler, game_name="patched_armor"),
    "Patched Skirt": SaltSanctuaryItemData(code=BASE_ID + 383, classification=ItemClassification.filler, game_name="patched_boots"),
    "Patched Gloves": SaltSanctuaryItemData(code=BASE_ID + 384, classification=ItemClassification.filler, game_name="patched_gloves"),
    "Patched Hood": SaltSanctuaryItemData(code=BASE_ID + 385, classification=ItemClassification.filler, game_name="patched_helm"),
    "Corsair's Vest": SaltSanctuaryItemData(code=BASE_ID + 386, classification=ItemClassification.filler, game_name="pirate_armor"),
    "Corsair's Boots": SaltSanctuaryItemData(code=BASE_ID + 387, classification=ItemClassification.filler, game_name="pirate_boots"),
    "Corsair's Bandana": SaltSanctuaryItemData(code=BASE_ID + 388, classification=ItemClassification.filler, game_name="pirate_helm"),
    "Amethyst Bodice": SaltSanctuaryItemData(code=BASE_ID + 389, classification=ItemClassification.filler, game_name="purpledress_armor"),
    "Amethyst Skirt": SaltSanctuaryItemData(code=BASE_ID + 390, classification=ItemClassification.filler, game_name="purpledress_boots"),
    "Amethyst Hood": SaltSanctuaryItemData(code=BASE_ID + 391, classification=ItemClassification.filler, game_name="purpledress_helm"),
    "Beggar's Rags": SaltSanctuaryItemData(code=BASE_ID + 392, classification=ItemClassification.filler, game_name="rags_armor"),
    "Beggar's Breeches": SaltSanctuaryItemData(code=BASE_ID + 393, classification=ItemClassification.filler, game_name="rags_boots"),
    "Beggar's Gloves": SaltSanctuaryItemData(code=BASE_ID + 394, classification=ItemClassification.filler, game_name="rags_gloves"),
    "Beggar's Hood": SaltSanctuaryItemData(code=BASE_ID + 395, classification=ItemClassification.filler, game_name="rags_helm"),
    "Crimson Tabard": SaltSanctuaryItemData(code=BASE_ID + 396, classification=ItemClassification.filler, game_name="redmage_armor"),
    "Crimson Culottes": SaltSanctuaryItemData(code=BASE_ID + 397, classification=ItemClassification.filler, game_name="redmage_boots"),
    "Crimson Gloves": SaltSanctuaryItemData(code=BASE_ID + 398, classification=ItemClassification.filler, game_name="redmage_gloves"),
    "Crimson Hood": SaltSanctuaryItemData(code=BASE_ID + 399, classification=ItemClassification.filler, game_name="redmage_helm"),
    "Grim Justacorps": SaltSanctuaryItemData(code=BASE_ID + 400, classification=ItemClassification.filler, game_name="ribs_armor"),
    "Grim Tassets": SaltSanctuaryItemData(code=BASE_ID + 401, classification=ItemClassification.filler, game_name="ribs_boots"),
    "Grim Bracelets": SaltSanctuaryItemData(code=BASE_ID + 402, classification=ItemClassification.filler, game_name="ribs_gloves"),
    "Grim Headdress": SaltSanctuaryItemData(code=BASE_ID + 403, classification=ItemClassification.filler, game_name="ribs_helm"),
    "Warden's Smock": SaltSanctuaryItemData(code=BASE_ID + 404, classification=ItemClassification.filler, game_name="rotten_armor"),
    "Warden's Chaps": SaltSanctuaryItemData(code=BASE_ID + 405, classification=ItemClassification.filler, game_name="rotten_boots"),
    "Warden's Gloves": SaltSanctuaryItemData(code=BASE_ID + 406, classification=ItemClassification.filler, game_name="rotten_gloves"),
    "Warden's Branks": SaltSanctuaryItemData(code=BASE_ID + 407, classification=ItemClassification.filler, game_name="rotten_helm"),
    "Tainted Cuirass": SaltSanctuaryItemData(code=BASE_ID + 408, classification=ItemClassification.filler, game_name="saltknight_armor"),
    "Tainted Greaves": SaltSanctuaryItemData(code=BASE_ID + 409, classification=ItemClassification.filler, game_name="saltknight_boots"),
    "Tainted Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 410, classification=ItemClassification.filler, game_name="saltknight_gloves"),
    "Tainted Armet": SaltSanctuaryItemData(code=BASE_ID + 411, classification=ItemClassification.filler, game_name="saltknight_helm"),
    "Demon Domaru": SaltSanctuaryItemData(code=BASE_ID + 412, classification=ItemClassification.filler, game_name="samurai_armor"),
    "Demon Haidate": SaltSanctuaryItemData(code=BASE_ID + 413, classification=ItemClassification.filler, game_name="samurai_boots"),
    "Demon Kote": SaltSanctuaryItemData(code=BASE_ID + 414, classification=ItemClassification.filler, game_name="samurai_gloves"),
    "Demon Kabuto": SaltSanctuaryItemData(code=BASE_ID + 415, classification=ItemClassification.filler, game_name="samurai_helm"),
    "Malva Tabard": SaltSanctuaryItemData(code=BASE_ID + 416, classification=ItemClassification.filler, game_name="slug_armor"),
    "Malva Pigaciae": SaltSanctuaryItemData(code=BASE_ID + 417, classification=ItemClassification.filler, game_name="slug_boots"),
    "Malva Cuffs": SaltSanctuaryItemData(code=BASE_ID + 418, classification=ItemClassification.filler, game_name="slug_gloves"),
    "Malva Koukoulion": SaltSanctuaryItemData(code=BASE_ID + 419, classification=ItemClassification.filler, game_name="slug_helm"),
    "Split Cuirass": SaltSanctuaryItemData(code=BASE_ID + 420, classification=ItemClassification.filler, game_name="split_armor"),
    "Split Sabatons": SaltSanctuaryItemData(code=BASE_ID + 421, classification=ItemClassification.filler, game_name="split_boots"),
    "Split Manifers": SaltSanctuaryItemData(code=BASE_ID + 422, classification=ItemClassification.filler, game_name="split_gloves"),
    "Split Mask": SaltSanctuaryItemData(code=BASE_ID + 423, classification=ItemClassification.filler, game_name="split_helm"),
    "Plate Mail": SaltSanctuaryItemData(code=BASE_ID + 424, classification=ItemClassification.filler, game_name="stag_armor"),
    "Plate Greaves": SaltSanctuaryItemData(code=BASE_ID + 425, classification=ItemClassification.filler, game_name="stag_boots"),
    "Plate Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 426, classification=ItemClassification.filler, game_name="stag_gloves"),
    "Russet Doublet": SaltSanctuaryItemData(code=BASE_ID + 427, classification=ItemClassification.filler, game_name="tater_armor"),
    "Russet Leggings": SaltSanctuaryItemData(code=BASE_ID + 428, classification=ItemClassification.filler, game_name="tater_boots"),
    "Russet Sleeves": SaltSanctuaryItemData(code=BASE_ID + 429, classification=ItemClassification.filler, game_name="tater_gloves"),
    "Russet Mask": SaltSanctuaryItemData(code=BASE_ID + 430, classification=ItemClassification.filler, game_name="tater_helm"),
    "Rogue's Jacket": SaltSanctuaryItemData(code=BASE_ID + 431, classification=ItemClassification.filler, game_name="thief_armor"),
    "Rogue's Highboots": SaltSanctuaryItemData(code=BASE_ID + 432, classification=ItemClassification.filler, game_name="thief_boots"),
    "Rogue's Gloves": SaltSanctuaryItemData(code=BASE_ID + 433, classification=ItemClassification.filler, game_name="thief_gloves"),
    "Rogue's Mask": SaltSanctuaryItemData(code=BASE_ID + 434, classification=ItemClassification.filler, game_name="thief_helm"),
    "Raider's Harness": SaltSanctuaryItemData(code=BASE_ID + 435, classification=ItemClassification.filler, game_name="tribe_armor"),
    "Raider's Portyanki": SaltSanctuaryItemData(code=BASE_ID + 436, classification=ItemClassification.filler, game_name="tribe_boots"),
    "Raider's Ushanka": SaltSanctuaryItemData(code=BASE_ID + 437, classification=ItemClassification.filler, game_name="tribe_helm"),
    "Cotton Tunic": SaltSanctuaryItemData(code=BASE_ID + 438, classification=ItemClassification.filler, game_name="tunic_armor"),
    "Cotton Trousers": SaltSanctuaryItemData(code=BASE_ID + 439, classification=ItemClassification.filler, game_name="tunic_boots"),
    "White Plate Armor": SaltSanctuaryItemData(code=BASE_ID + 440, classification=ItemClassification.filler, game_name="white_armor"),
    "White Greaves": SaltSanctuaryItemData(code=BASE_ID + 441, classification=ItemClassification.filler, game_name="white_boots"),
    "White Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 442, classification=ItemClassification.filler, game_name="white_gloves"),
    "Royalist's Armet": SaltSanctuaryItemData(code=BASE_ID + 443, classification=ItemClassification.filler, game_name="white_helm"),
    "Evanescent Cassock": SaltSanctuaryItemData(code=BASE_ID + 444, classification=ItemClassification.filler, game_name="whitedress_armor"),
    "Evanescent Cincture": SaltSanctuaryItemData(code=BASE_ID + 445, classification=ItemClassification.filler, game_name="whitedress_boots"),
    "Evanescent Cowl": SaltSanctuaryItemData(code=BASE_ID + 446, classification=ItemClassification.filler, game_name="whitedress_helm"),
    "Breastplate of the Wolf": SaltSanctuaryItemData(code=BASE_ID + 447, classification=ItemClassification.filler, game_name="wolf_armor"),
    "Boots of the Wolf": SaltSanctuaryItemData(code=BASE_ID + 448, classification=ItemClassification.filler, game_name="wolf_boots"),
    "Aristocrat's Corset": SaltSanctuaryItemData(code=BASE_ID + 449, classification=ItemClassification.filler, game_name="armor_reddress"),
    "Sorcerer's Kurta": SaltSanctuaryItemData(code=BASE_ID + 450, classification=ItemClassification.filler, game_name="armor_sorceror"),
    "Aristocrat's Crinolette": SaltSanctuaryItemData(code=BASE_ID + 451, classification=ItemClassification.filler, game_name="boots_reddress"),
    "Sorcerer's Lungi": SaltSanctuaryItemData(code=BASE_ID + 452, classification=ItemClassification.filler, game_name="boots_sorceror"),
    "Aristocrat's Veil": SaltSanctuaryItemData(code=BASE_ID + 453, classification=ItemClassification.filler, game_name="reddress_helm"),
    "Jute Tunic": SaltSanctuaryItemData(code=BASE_ID + 454, classification=ItemClassification.filler, game_name="salad_armor"),
    "Jute Breeches": SaltSanctuaryItemData(code=BASE_ID + 455, classification=ItemClassification.filler, game_name="salad_boots"),
    "Yokai Mask": SaltSanctuaryItemData(code=BASE_ID + 456, classification=ItemClassification.filler, game_name="bloodeye_helm"),
    "Clay Mask": SaltSanctuaryItemData(code=BASE_ID + 457, classification=ItemClassification.filler, game_name="claymask_helm"),
    "Mask of Splendor": SaltSanctuaryItemData(code=BASE_ID + 458, classification=ItemClassification.filler, game_name="goldmask_helm"),
    "Pigeon Mask": SaltSanctuaryItemData(code=BASE_ID + 459, classification=ItemClassification.filler, game_name="pigeonmask_helm"),
    "Ghastly Gourd": SaltSanctuaryItemData(code=BASE_ID + 460, classification=ItemClassification.filler, game_name="pumpkin_helm"),
    "Sadist's Veil": SaltSanctuaryItemData(code=BASE_ID + 461, classification=ItemClassification.filler, game_name="torturer_bow_mask"),
    "Torturer's Veil": SaltSanctuaryItemData(code=BASE_ID + 462, classification=ItemClassification.filler, game_name="torturer_mask"),
    "Predator Cuirass": SaltSanctuaryItemData(code=BASE_ID + 463, classification=ItemClassification.filler, game_name="gold_archer_armor"),
    "Predator Sabatons": SaltSanctuaryItemData(code=BASE_ID + 464, classification=ItemClassification.filler, game_name="gold_archer_boots"),
    "Predator Gauntlets": SaltSanctuaryItemData(code=BASE_ID + 465, classification=ItemClassification.filler, game_name="gold_archer_gloves"),
    "Predator Bascinet": SaltSanctuaryItemData(code=BASE_ID + 466, classification=ItemClassification.filler, game_name="gold_archer_helm"),
    "Arrow": SaltSanctuaryItemData(code=BASE_ID + 467, classification=ItemClassification.filler, game_name="arrow"),
    "Steel Arrow": SaltSanctuaryItemData(code=BASE_ID + 468, classification=ItemClassification.filler, game_name="arrow_big"),
    "Flame Arrow": SaltSanctuaryItemData(code=BASE_ID + 469, classification=ItemClassification.filler, game_name="arrow_flame"),
    "Poison Arrow": SaltSanctuaryItemData(code=BASE_ID + 470, classification=ItemClassification.filler, game_name="arrow_poison"),
    "Bolt": SaltSanctuaryItemData(code=BASE_ID + 471, classification=ItemClassification.filler, game_name="bolt"),
    "Flame Bolt": SaltSanctuaryItemData(code=BASE_ID + 472, classification=ItemClassification.filler, game_name="bolt_flame"),
    "Poison Bolt": SaltSanctuaryItemData(code=BASE_ID + 473, classification=ItemClassification.filler, game_name="bolt_poison"),
    "Flintlock Shot": SaltSanctuaryItemData(code=BASE_ID + 474, classification=ItemClassification.filler, game_name="flintshot"),
    "Glowing Shot": SaltSanctuaryItemData(code=BASE_ID + 475, classification=ItemClassification.filler, game_name="flintshot_lit"),
    "Tainted Shot": SaltSanctuaryItemData(code=BASE_ID + 476, classification=ItemClassification.filler, game_name="flintshot_poison"),
    "Red Flask": SaltSanctuaryItemData(code=BASE_ID + 477, classification=ItemClassification.filler, game_name="potion"),
    "Orange Phial": SaltSanctuaryItemData(code=BASE_ID + 478, classification=ItemClassification.filler, game_name="potion_holy"),
    "Antidote": SaltSanctuaryItemData(code=BASE_ID + 479, classification=ItemClassification.filler, game_name="antidote"),
    "Blood Vial": SaltSanctuaryItemData(code=BASE_ID + 480, classification=ItemClassification.filler, game_name="blood_vial"),
    "Red Grass": SaltSanctuaryItemData(code=BASE_ID + 481, classification=ItemClassification.filler, game_name="heal_herb"),
    "Red Shard": SaltSanctuaryItemData(code=BASE_ID + 482, classification=ItemClassification.filler, game_name="health_shard"),
    "Blue Grass": SaltSanctuaryItemData(code=BASE_ID + 483, classification=ItemClassification.filler, game_name="mana_herb"),
    "Blue Crystal": SaltSanctuaryItemData(code=BASE_ID + 484, classification=ItemClassification.filler, game_name="mana_crystal"),
    "Sky Shard": SaltSanctuaryItemData(code=BASE_ID + 485, classification=ItemClassification.filler, game_name="mp_shard"),
    "Spiced Mead": SaltSanctuaryItemData(code=BASE_ID + 486, classification=ItemClassification.filler, game_name="mana_mead"),
    "Goldenwine": SaltSanctuaryItemData(code=BASE_ID + 487, classification=ItemClassification.filler, game_name="gold_wine"),
    "Iris Wine": SaltSanctuaryItemData(code=BASE_ID + 488, classification=ItemClassification.filler, game_name="blue_wine"),
    "Lilyred Wine": SaltSanctuaryItemData(code=BASE_ID + 489, classification=ItemClassification.filler, game_name="red_wine"),
    "Hearty Roll": SaltSanctuaryItemData(code=BASE_ID + 490, classification=ItemClassification.filler, game_name="roll"),
    "Phial of Undersight": SaltSanctuaryItemData(code=BASE_ID + 491, classification=ItemClassification.filler, game_name="vision_potion"),
    "Sky Crystal": SaltSanctuaryItemData(code=BASE_ID + 492, classification=ItemClassification.filler, game_name="buff_crystal"),
    "Stained Page": SaltSanctuaryItemData(code=BASE_ID + 493, classification=ItemClassification.filler, game_name="buff_dark"),
    "Pitchfire": SaltSanctuaryItemData(code=BASE_ID + 494, classification=ItemClassification.filler, game_name="buff_fire"),
    "Frostgel": SaltSanctuaryItemData(code=BASE_ID + 495, classification=ItemClassification.filler, game_name="buff_frost"),
    "Blessed Page": SaltSanctuaryItemData(code=BASE_ID + 496, classification=ItemClassification.filler, game_name="buff_holy"),
    "Shockstone": SaltSanctuaryItemData(code=BASE_ID + 497, classification=ItemClassification.filler, game_name="buff_lit"),
    "Pessmud": SaltSanctuaryItemData(code=BASE_ID + 498, classification=ItemClassification.filler, game_name="buff_poison"),
    "Page of Suffering": SaltSanctuaryItemData(code=BASE_ID + 499, classification=ItemClassification.filler, game_name="buff_sancdark"),
    "Imperial Pitchfire": SaltSanctuaryItemData(code=BASE_ID + 500, classification=ItemClassification.filler, game_name="buff_sancfire"),
    "Clarity": SaltSanctuaryItemData(code=BASE_ID + 501, classification=ItemClassification.filler, game_name="buff_sancfocus"),
    "Sky Frostgel": SaltSanctuaryItemData(code=BASE_ID + 502, classification=ItemClassification.filler, game_name="buff_sancfrost"),
    "Page of Light": SaltSanctuaryItemData(code=BASE_ID + 503, classification=ItemClassification.filler, game_name="buff_sancholy"),
    "Metal Shockstone": SaltSanctuaryItemData(code=BASE_ID + 504, classification=ItemClassification.filler, game_name="buff_sanclit"),
    "Mossy Pessmud": SaltSanctuaryItemData(code=BASE_ID + 505, classification=ItemClassification.filler, game_name="buff_sancpoison"),
    "Imperial Shockstone": SaltSanctuaryItemData(code=BASE_ID + 506, classification=ItemClassification.filler, game_name="buff_threelit"),
    "Grenado": SaltSanctuaryItemData(code=BASE_ID + 507, classification=ItemClassification.filler, game_name="grenado"),
    "Birian Firepot": SaltSanctuaryItemData(code=BASE_ID + 508, classification=ItemClassification.filler, game_name="firepot"),
    "Torch": SaltSanctuaryItemData(code=BASE_ID + 509, classification=ItemClassification.filler, game_name="torch"),
    "Repair Kit": SaltSanctuaryItemData(code=BASE_ID + 510, classification=ItemClassification.filler, game_name="repair_kit"),
    "Cleansing Cloth": SaltSanctuaryItemData(code=BASE_ID + 511, classification=ItemClassification.filler, game_name="cleansing_cloth"),
    "Cloth of Blessing": SaltSanctuaryItemData(code=BASE_ID + 512, classification=ItemClassification.filler, game_name="mana_cloth"),
    "Sacred Linens": SaltSanctuaryItemData(code=BASE_ID + 513, classification=ItemClassification.filler, game_name="holy_bandage"),
    "Water of Blessing": SaltSanctuaryItemData(code=BASE_ID + 514, classification=ItemClassification.filler, game_name="water"),
    "Lightvessel": SaltSanctuaryItemData(code=BASE_ID + 515, classification=ItemClassification.filler, game_name="waterpot"),
    "Throwing Dagger": SaltSanctuaryItemData(code=BASE_ID + 516, classification=ItemClassification.filler, game_name="throw_dagger"),
    "Dragon's Tooth": SaltSanctuaryItemData(code=BASE_ID + 517, classification=ItemClassification.filler, game_name="throw_f_dagger"),
    "Forestfang": SaltSanctuaryItemData(code=BASE_ID + 518, classification=ItemClassification.filler, game_name="throw_p_dagger"),
    "Potato": SaltSanctuaryItemData(code=BASE_ID + 519, classification=ItemClassification.filler, game_name="throw_potato"),
    "Wraithfang": SaltSanctuaryItemData(code=BASE_ID + 520, classification=ItemClassification.filler, game_name="throw_w_dagger"),
    "Egg of Wrath": SaltSanctuaryItemData(code=BASE_ID + 521, classification=ItemClassification.filler, game_name="egg_wrath"),
    "Flask of Defilement": SaltSanctuaryItemData(code=BASE_ID + 522, classification=ItemClassification.filler, game_name="blood_pot"),
    "Flask of Fire": SaltSanctuaryItemData(code=BASE_ID + 523, classification=ItemClassification.filler, game_name="fire_flask"),
    "Sellsword's Bell": SaltSanctuaryItemData(code=BASE_ID + 680, classification=ItemClassification.filler, game_name="coop_bell"),
    "Bell of Return": SaltSanctuaryItemData(code=BASE_ID + 524, classification=ItemClassification.filler, game_name="return_bell"),
    "Jurney Bottle": SaltSanctuaryItemData(code=BASE_ID + 525, classification=ItemClassification.filler, game_name="msg_bottle"),
    "Green Jurney Bottle": SaltSanctuaryItemData(code=BASE_ID + 526, classification=ItemClassification.filler, game_name="msg_bottle_green"),
    "Calling Horn": SaltSanctuaryItemData(code=BASE_ID + 527, classification=ItemClassification.filler, game_name="horn_guide"),
    "Mountain Warhorn": SaltSanctuaryItemData(code=BASE_ID + 528, classification=ItemClassification.filler, game_name="horn_sanc_will"),
    "Warhorn": SaltSanctuaryItemData(code=BASE_ID + 529, classification=ItemClassification.filler, game_name="horn_will"),
    "Pouch of Salt": SaltSanctuaryItemData(code=BASE_ID + 530, classification=ItemClassification.filler, game_name="salt1"),
    "Bundle of Salt": SaltSanctuaryItemData(code=BASE_ID + 531, classification=ItemClassification.filler, game_name="salt2"),
    "Bag of Salt": SaltSanctuaryItemData(code=BASE_ID + 532, classification=ItemClassification.filler, game_name="salt3"),
    "Sack of Salt": SaltSanctuaryItemData(code=BASE_ID + 533, classification=ItemClassification.filler, game_name="salt4"),
    "Satchel of Salt": SaltSanctuaryItemData(code=BASE_ID + 534, classification=ItemClassification.filler, game_name="salt5"),
    "Pack of Salt": SaltSanctuaryItemData(code=BASE_ID + 535, classification=ItemClassification.filler, game_name="salt6"),
    "Case of Salt": SaltSanctuaryItemData(code=BASE_ID + 536, classification=ItemClassification.filler, game_name="salt7"),
    "Box of Salt": SaltSanctuaryItemData(code=BASE_ID + 537, classification=ItemClassification.filler, game_name="salt8"),
    "Crate of Salt": SaltSanctuaryItemData(code=BASE_ID + 538, classification=ItemClassification.filler, game_name="salt9"),
    "Chest of Salt": SaltSanctuaryItemData(code=BASE_ID + 539, classification=ItemClassification.filler, game_name="salt10"),
    "Black Salt": SaltSanctuaryItemData(code=BASE_ID + 540, classification=ItemClassification.filler, game_name="black_salt"),
    "Bag of Earth": SaltSanctuaryItemData(code=BASE_ID + 541, classification=ItemClassification.filler, game_name="earth_bag"),
    "Crystal Sphere": SaltSanctuaryItemData(code=BASE_ID + 542, classification=ItemClassification.filler, game_name="crystal_sphere"),
    "Gray Pearl": SaltSanctuaryItemData(code=BASE_ID + 543, classification=ItemClassification.filler, game_name="gray_pearl"),
    "Black Pearl": SaltSanctuaryItemData(code=BASE_ID + 544, classification=ItemClassification.filler, game_name="black_pearl"),
    "Bloody Writ": SaltSanctuaryItemData(code=BASE_ID + 545, classification=ItemClassification.filler, game_name="bloody_writ"),
    "Expunged Heart": SaltSanctuaryItemData(code=BASE_ID + 546, classification=ItemClassification.filler, game_name="expunged_heart"),
    "Dark Coil": SaltSanctuaryItemData(code=BASE_ID + 547, classification=ItemClassification.filler, game_name="dark_coil"),
    "Dark Reach": SaltSanctuaryItemData(code=BASE_ID + 548, classification=ItemClassification.filler, game_name="dark_coil2"),
    "Diamond Cluster": SaltSanctuaryItemData(code=BASE_ID + 549, classification=ItemClassification.filler, game_name="amber_blaze"),
    "Amber Idol": SaltSanctuaryItemData(code=BASE_ID + 550, classification=ItemClassification.filler, game_name="amber_flame"),
    "Shimmering Pearl": SaltSanctuaryItemData(code=BASE_ID + 551, classification=ItemClassification.filler, game_name="amber_nova"),
    "Silver Leaf": SaltSanctuaryItemData(code=BASE_ID + 552, classification=ItemClassification.filler, game_name="amber_spark"),
    "Enduring Skull": SaltSanctuaryItemData(code=BASE_ID + 553, classification=ItemClassification.filler, game_name="beast_blaze"),
    "Hateful Jawbone": SaltSanctuaryItemData(code=BASE_ID + 554, classification=ItemClassification.filler, game_name="beast_flame"),
    "Twisted Heart": SaltSanctuaryItemData(code=BASE_ID + 555, classification=ItemClassification.filler, game_name="beast_nova"),
    "Endless Fang": SaltSanctuaryItemData(code=BASE_ID + 556, classification=ItemClassification.filler, game_name="beast_spark"),
    "Black Blaze": SaltSanctuaryItemData(code=BASE_ID + 557, classification=ItemClassification.filler, game_name="black_blaze"),
    "Black Flame": SaltSanctuaryItemData(code=BASE_ID + 558, classification=ItemClassification.filler, game_name="black_flame"),
    "Black Nova": SaltSanctuaryItemData(code=BASE_ID + 559, classification=ItemClassification.filler, game_name="black_nova"),
    "Black Spark": SaltSanctuaryItemData(code=BASE_ID + 560, classification=ItemClassification.filler, game_name="black_spark"),
    "Frozen Reliquary": SaltSanctuaryItemData(code=BASE_ID + 561, classification=ItemClassification.filler, game_name="blue_blaze"),
    "Frozen Locket": SaltSanctuaryItemData(code=BASE_ID + 562, classification=ItemClassification.filler, game_name="blue_flame"),
    "Frozen Tome": SaltSanctuaryItemData(code=BASE_ID + 563, classification=ItemClassification.filler, game_name="blue_nova"),
    "Frozen Doll": SaltSanctuaryItemData(code=BASE_ID + 564, classification=ItemClassification.filler, game_name="blue_spark"),
    "Bottled Sky": SaltSanctuaryItemData(code=BASE_ID + 565, classification=ItemClassification.filler, game_name="blue_sky"),
    "Drowned Censer": SaltSanctuaryItemData(code=BASE_ID + 566, classification=ItemClassification.filler, game_name="drowning_blaze"),
    "Drowned Locket": SaltSanctuaryItemData(code=BASE_ID + 567, classification=ItemClassification.filler, game_name="drowning_flame"),
    "Drowned Tome": SaltSanctuaryItemData(code=BASE_ID + 568, classification=ItemClassification.filler, game_name="drowning_nova"),
    "Drowned Idol": SaltSanctuaryItemData(code=BASE_ID + 569, classification=ItemClassification.filler, game_name="drowning_spark"),
    "Charred Reliquary": SaltSanctuaryItemData(code=BASE_ID + 570, classification=ItemClassification.filler, game_name="red_blaze"),
    "Charred Locket": SaltSanctuaryItemData(code=BASE_ID + 571, classification=ItemClassification.filler, game_name="red_flame"),
    "Charred Tome": SaltSanctuaryItemData(code=BASE_ID + 572, classification=ItemClassification.filler, game_name="red_nova"),
    "Charred Doll": SaltSanctuaryItemData(code=BASE_ID + 573, classification=ItemClassification.filler, game_name="red_spark"),
    "A Lord's Orders": SaltSanctuaryItemData(code=BASE_ID + 574, classification=ItemClassification.filler, game_name="white_blaze"),
    "A Soldier's Poem": SaltSanctuaryItemData(code=BASE_ID + 575, classification=ItemClassification.filler, game_name="white_flame"),
    "A King's Orders": SaltSanctuaryItemData(code=BASE_ID + 576, classification=ItemClassification.filler, game_name="white_nova"),
    "Lock of Hair": SaltSanctuaryItemData(code=BASE_ID + 577, classification=ItemClassification.filler, game_name="white_spark"),
    "The Mad Alchemist's Ear": SaltSanctuaryItemData(code=BASE_ID + 578, classification=ItemClassification.filler, game_name="dice_alchemist"),
    "Cave Keeper's Ear": SaltSanctuaryItemData(code=BASE_ID + 579, classification=ItemClassification.filler, game_name="dice_angler"),
    "Drowned Archer's Ear": SaltSanctuaryItemData(code=BASE_ID + 580, classification=ItemClassification.filler, game_name="dice_archer"),
    "Thing of Arms' Ear": SaltSanctuaryItemData(code=BASE_ID + 581, classification=ItemClassification.filler, game_name="dice_arms"),
    "Lepris' Ear": SaltSanctuaryItemData(code=BASE_ID + 582, classification=ItemClassification.filler, game_name="dice_bandages"),
    "Drowned Bandit's Ear": SaltSanctuaryItemData(code=BASE_ID + 583, classification=ItemClassification.filler, game_name="dice_bandit"),
    "Skullbat Wing": SaltSanctuaryItemData(code=BASE_ID + 584, classification=ItemClassification.filler, game_name="dice_bat"),
    "Mother Merle's Beak": SaltSanctuaryItemData(code=BASE_ID + 585, classification=ItemClassification.filler, game_name="dice_birdy"),
    "Poison Cytoplasm Gel": SaltSanctuaryItemData(code=BASE_ID + 586, classification=ItemClassification.filler, game_name="dice_blob"),
    "Vexing Brat's Ear": SaltSanctuaryItemData(code=BASE_ID + 587, classification=ItemClassification.filler, game_name="dice_bluetroll"),
    "Vacant Blades' Ashes": SaltSanctuaryItemData(code=BASE_ID + 588, classification=ItemClassification.filler, game_name="dice_bluewraith"),
    "Ronin Cran's Ashes": SaltSanctuaryItemData(code=BASE_ID + 589, classification=ItemClassification.filler, game_name="dice_broken"),
    "Kraekan Cyclops' Horn": SaltSanctuaryItemData(code=BASE_ID + 590, classification=ItemClassification.filler, game_name="dice_bull"),
    "Murdiella Mal's Ashes": SaltSanctuaryItemData(code=BASE_ID + 591, classification=ItemClassification.filler, game_name="dice_butterfly"),
    "The Bloodless Prince's Ashes": SaltSanctuaryItemData(code=BASE_ID + 592, classification=ItemClassification.filler, game_name="dice_clay"),
    "Carsejaw the Cruel's Ashes": SaltSanctuaryItemData(code=BASE_ID + 593, classification=ItemClassification.filler, game_name="dice_cloak"),
    "Armor Mite Chitin": SaltSanctuaryItemData(code=BASE_ID + 594, classification=ItemClassification.filler, game_name="dice_crab"),
    "Crypt Keeper's Ashes": SaltSanctuaryItemData(code=BASE_ID + 595, classification=ItemClassification.filler, game_name="dice_cryptkeeper"),
    "Saltless' Ashes": SaltSanctuaryItemData(code=BASE_ID + 596, classification=ItemClassification.filler, game_name="dice_cult"),
    "The Queen Of Smiles' Ear": SaltSanctuaryItemData(code=BASE_ID + 597, classification=ItemClassification.filler, game_name="dice_cutqueen"),
    "The Forgotten Judge's Ear": SaltSanctuaryItemData(code=BASE_ID + 598, classification=ItemClassification.filler, game_name="dice_deadjudge"),
    "The Forgotten King's Ear": SaltSanctuaryItemData(code=BASE_ID + 599, classification=ItemClassification.filler, game_name="dice_deadking"),
    "The Forgotten Knight's Ear": SaltSanctuaryItemData(code=BASE_ID + 600, classification=ItemClassification.filler, game_name="dice_deadknight"),
    "Feral Beast Tooth": SaltSanctuaryItemData(code=BASE_ID + 601, classification=ItemClassification.filler, game_name="dice_dog"),
    "Drowned Porcelain's Ashes": SaltSanctuaryItemData(code=BASE_ID + 602, classification=ItemClassification.filler, game_name="dice_doll"),
    "Kraekan Wyrm's Horn": SaltSanctuaryItemData(code=BASE_ID + 603, classification=ItemClassification.filler, game_name="dice_dragon"),
    "The Sodden Knight's Ashes": SaltSanctuaryItemData(code=BASE_ID + 604, classification=ItemClassification.filler, game_name="dice_dread"),
    "Drowned Berzerker's Ear": SaltSanctuaryItemData(code=BASE_ID + 605, classification=ItemClassification.filler, game_name="dice_drowned"),
    "Heartseeker Nerves": SaltSanctuaryItemData(code=BASE_ID + 606, classification=ItemClassification.filler, game_name="dice_eyeball"),
    "Bola Eye Nerves": SaltSanctuaryItemData(code=BASE_ID + 607, classification=ItemClassification.filler, game_name="dice_eyescorpion"),
    "The False Jester's Ear": SaltSanctuaryItemData(code=BASE_ID + 608, classification=ItemClassification.filler, game_name="dice_fauxjester"),
    "Retchfeeder Maw": SaltSanctuaryItemData(code=BASE_ID + 609, classification=ItemClassification.filler, game_name="dice_fiend"),
    "Gaoler's Ear": SaltSanctuaryItemData(code=BASE_ID + 610, classification=ItemClassification.filler, game_name="dice_gaoler"),
    "That Stench Most Foul's Tooth": SaltSanctuaryItemData(code=BASE_ID + 611, classification=ItemClassification.filler, game_name="dice_gasbag"),
    "Whisperman's Ashes": SaltSanctuaryItemData(code=BASE_ID + 612, classification=ItemClassification.filler, game_name="dice_ghost"),
    "Whisperlady's Ashes": SaltSanctuaryItemData(code=BASE_ID + 613, classification=ItemClassification.filler, game_name="dice_ghostwitch"),
    "Hornet Steel's Ashes": SaltSanctuaryItemData(code=BASE_ID + 614, classification=ItemClassification.filler, game_name="dice_gold_archer"),
    "Armor Guardian's Ashes": SaltSanctuaryItemData(code=BASE_ID + 615, classification=ItemClassification.filler, game_name="dice_golem"),
    "Flying Spider's Tusk": SaltSanctuaryItemData(code=BASE_ID + 616, classification=ItemClassification.filler, game_name="dice_greenspider"),
    "Sanctuary Guard's Ear": SaltSanctuaryItemData(code=BASE_ID + 617, classification=ItemClassification.filler, game_name="dice_guardian"),
    "Red Lord's Ear": SaltSanctuaryItemData(code=BASE_ID + 618, classification=ItemClassification.filler, game_name="dice_guardian_rotten"),
    "Hanged Man's Rope": SaltSanctuaryItemData(code=BASE_ID + 619, classification=ItemClassification.filler, game_name="dice_hangman"),
    "Vilehawk's Ear": SaltSanctuaryItemData(code=BASE_ID + 620, classification=ItemClassification.filler, game_name="dice_hawk"),
    "The Third Lamb's Beak": SaltSanctuaryItemData(code=BASE_ID + 621, classification=ItemClassification.filler, game_name="dice_hippogriff"),
    "Caged Man's Ear": SaltSanctuaryItemData(code=BASE_ID + 622, classification=ItemClassification.filler, game_name="dice_hookman"),
    "Horsehead's Ear": SaltSanctuaryItemData(code=BASE_ID + 623, classification=ItemClassification.filler, game_name="dice_horsehead"),
    "Dread Horseman's Ashes": SaltSanctuaryItemData(code=BASE_ID + 624, classification=ItemClassification.filler, game_name="dice_horseknight"),
    "Spear Imp's Horn": SaltSanctuaryItemData(code=BASE_ID + 625, classification=ItemClassification.filler, game_name="dice_imp"),
    "The Untouched Inquisitor's Ashes": SaltSanctuaryItemData(code=BASE_ID + 626, classification=ItemClassification.filler, game_name="dice_inquisitor"),
    "Bronze Knight Ashes": SaltSanctuaryItemData(code=BASE_ID + 627, classification=ItemClassification.filler, game_name="dice_knight"),
    "Bronze Axe Knight's Ashes": SaltSanctuaryItemData(code=BASE_ID + 628, classification=ItemClassification.filler, game_name="dice_knight_axe"),
    "The Witch of the Lake's Ear": SaltSanctuaryItemData(code=BASE_ID + 629, classification=ItemClassification.filler, game_name="dice_lakewitch"),
    "Lietch Rib": SaltSanctuaryItemData(code=BASE_ID + 630, classification=ItemClassification.filler, game_name="dice_lich"),
    "The Unskinned's Liver": SaltSanctuaryItemData(code=BASE_ID + 631, classification=ItemClassification.filler, game_name="dice_monster"),
    "The Architect's Ear": SaltSanctuaryItemData(code=BASE_ID + 632, classification=ItemClassification.filler, game_name="dice_monsterwitch"),
    "The Dried King's Ashes": SaltSanctuaryItemData(code=BASE_ID + 633, classification=ItemClassification.filler, game_name="dice_mummy"),
    "The Nameless God's Ashes": SaltSanctuaryItemData(code=BASE_ID + 634, classification=ItemClassification.filler, game_name="dice_nameless"),
    "Wrathful Dead's Bindings": SaltSanctuaryItemData(code=BASE_ID + 635, classification=ItemClassification.filler, game_name="dice_nightmare"),
    "Bloated Monstrosity's Ear": SaltSanctuaryItemData(code=BASE_ID + 636, classification=ItemClassification.filler, game_name="dice_ogre"),
    "Clay Phantom's Ashes": SaltSanctuaryItemData(code=BASE_ID + 637, classification=ItemClassification.filler, game_name="dice_phantasm"),
    "Disemboweled Husk's Doll": SaltSanctuaryItemData(code=BASE_ID + 638, classification=ItemClassification.filler, game_name="dice_pirate"),
    "Drowned Peasant's Ear": SaltSanctuaryItemData(code=BASE_ID + 639, classification=ItemClassification.filler, game_name="dice_rags"),
    "Drowned Raider's Ear": SaltSanctuaryItemData(code=BASE_ID + 640, classification=ItemClassification.filler, game_name="dice_raider"),
    "The Coveted's Ashes": SaltSanctuaryItemData(code=BASE_ID + 641, classification=ItemClassification.filler, game_name="dice_ruinaxe"),
    "Alkymancery Knight's Ashes": SaltSanctuaryItemData(code=BASE_ID + 642, classification=ItemClassification.filler, game_name="dice_saltknight"),
    "Angsty Bones' Rib": SaltSanctuaryItemData(code=BASE_ID + 643, classification=ItemClassification.filler, game_name="dice_skeleton"),
    "Hunting Bones' Rib": SaltSanctuaryItemData(code=BASE_ID + 644, classification=ItemClassification.filler, game_name="dice_skeleton_archer"),
    "Primitive Bones' Rib": SaltSanctuaryItemData(code=BASE_ID + 645, classification=ItemClassification.filler, game_name="dice_skeleton_tribe"),
    "Emberskull's Ashes": SaltSanctuaryItemData(code=BASE_ID + 646, classification=ItemClassification.filler, game_name="dice_skull"),
    "Drowned Soldier's Ear": SaltSanctuaryItemData(code=BASE_ID + 647, classification=ItemClassification.filler, game_name="dice_soldier"),
    "Court Sorceror's Ear": SaltSanctuaryItemData(code=BASE_ID + 648, classification=ItemClassification.filler, game_name="dice_sorceror"),
    "Bedspider's Tusk": SaltSanctuaryItemData(code=BASE_ID + 649, classification=ItemClassification.filler, game_name="dice_spider"),
    "Dropspider's Tusk": SaltSanctuaryItemData(code=BASE_ID + 650, classification=ItemClassification.filler, game_name="dice_spider_blue"),
    "Split Swordsman's Ear": SaltSanctuaryItemData(code=BASE_ID + 651, classification=ItemClassification.filler, game_name="dice_split"),
    "Skourzh's Horn": SaltSanctuaryItemData(code=BASE_ID + 652, classification=ItemClassification.filler, game_name="dice_squiddragon"),
    "Gravewalker's Ashes": SaltSanctuaryItemData(code=BASE_ID + 653, classification=ItemClassification.filler, game_name="dice_stonesoul"),
    "Torturer's Ear": SaltSanctuaryItemData(code=BASE_ID + 654, classification=ItemClassification.filler, game_name="dice_torturer"),
    "Vile Guard's Ear": SaltSanctuaryItemData(code=BASE_ID + 655, classification=ItemClassification.filler, game_name="dice_torturer_bow"),
    "The Tree of Men's Ashes": SaltSanctuaryItemData(code=BASE_ID + 656, classification=ItemClassification.filler, game_name="dice_torturetree"),
    "Arrox's Ear": SaltSanctuaryItemData(code=BASE_ID + 657, classification=ItemClassification.filler, game_name="dice_troll"),
    "Pale Witch's Ear": SaltSanctuaryItemData(code=BASE_ID + 658, classification=ItemClassification.filler, game_name="dice_witch"),
    "Blade Wraith Rib": SaltSanctuaryItemData(code=BASE_ID + 659, classification=ItemClassification.filler, game_name="dice_wraith"),
    "Rotten Walker's Ear": SaltSanctuaryItemData(code=BASE_ID + 660, classification=ItemClassification.filler, game_name="dice_zombie"),
    "Rotten Raider's Ear": SaltSanctuaryItemData(code=BASE_ID + 661, classification=ItemClassification.filler, game_name="dice_zomblack"),
    # Creed icons (icon_*) removed - they corrupt sanctuary state when granted via Archipelago
    # Players can still obtain them normally in-game from creed NPCs
    "Stone Alchemist": SaltSanctuaryItemData(code=BASE_ID + 671, classification=ItemClassification.filler, game_name="statue_alchemist"),
    "Stone Blacksmith": SaltSanctuaryItemData(code=BASE_ID + 672, classification=ItemClassification.filler, game_name="statue_blacksmith"),
    "Stone Cleric": SaltSanctuaryItemData(code=BASE_ID + 673, classification=ItemClassification.filler, game_name="statue_cleric"),
    "Stone Guide": SaltSanctuaryItemData(code=BASE_ID + 674, classification=ItemClassification.filler, game_name="statue_guide"),
    "Stone Leader": SaltSanctuaryItemData(code=BASE_ID + 675, classification=ItemClassification.filler, game_name="statue_leader"),
    "Stone Mage": SaltSanctuaryItemData(code=BASE_ID + 676, classification=ItemClassification.filler, game_name="statue_mage"),
    "Stone Merchant": SaltSanctuaryItemData(code=BASE_ID + 677, classification=ItemClassification.filler, game_name="statue_merchant"),
    "Stone Sellsword": SaltSanctuaryItemData(code=BASE_ID + 678, classification=ItemClassification.filler, game_name="statue_sellsword"),
    "Stone Mystic": SaltSanctuaryItemData(code=BASE_ID + 679, classification=ItemClassification.filler, game_name="statue_summoner"),
}

# Total items: 672 (9 creed icons removed)


# Helper lookups
item_name_to_id = {name: data.code for name, data in item_table.items()}
item_id_to_name = {data.code: name for name, data in item_table.items()}
game_name_to_item = {data.game_name: name for name, data in item_table.items()}

